# .github/workflows/release.yaml
name: Auto Release on Tag

on:
  push:
    tags:
      - 'v*'  # Триггерится только при пуше тега, начинающегося с 'v', например: v1.0.0

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run tests
        run: go test -v ./...

  release:
    name: Release Binaries
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: "386"
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: "386"
          - goos: darwin
            goarch: amd64
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # Опционально: добавь файлы
          # extra_files: LICENSE README.md
          sha256sum: true
